### PR TITLE
Add feature to check PEP515 in CLI

### LINKED ISSUE #72: argument consisting of digit + underscore will be parsed incorrectly
## Purpose
- bug report

## Description

```bash
# incorrect record id
$ pydtk model generate metadata --record_id "0000_0000" --from_file test.csv
{
    "record_id": 0,
    "path": "/work5/t_hayashi/work/pydtk/test.csv",
    "contents": {
        "content": {
            "columns": [
                "test"
            ],
            "tags": [
                "csv"
            ]
        }
    }
}

# OK
$ pydtk model generate metadata --record_id "0000__0000" --from_file test.csv
{
    "record_id": "0000__0000",
    "path": "/work5/t_hayashi/work/pydtk/test.csv",
    "contents": {
        "content": {
            "columns": [
                "test"
            ],
            "tags": [
                "csv"
            ]
        }
    }
}

# OK
$ pydtk model generate metadata --record_id "a0000_0000" --from_file test.csv
{
    "record_id": "a0000_0000",
    "path": "/work5/t_hayashi/work/pydtk/test.csv",
    "contents": {
        "content": {
            "columns": [
                "test"
            ],
            "tags": [
                "csv"
            ]
        }
    }
}
```

### PR DESCRIPTION
**Pull request by d-hayashi**
## What?
Resolve #72 

## Why?
To improve usability

### CODE REVIEW

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/pydtk/pull/77#" title="Author self-approved">d-hayashi</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fpydtk).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/pydtk/blob/master/OWNERS)~~ [d-hayashi]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by sudach — APPROVED** [review]
LGTM

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/pydtk/pull/77#" title="Author self-approved">d-hayashi</a>*, *<a href="https://github.com/dataware-tools/pydtk/pull/77#pullrequestreview-709122812" title="Approved">sudach</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fpydtk).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/pydtk/blob/master/OWNERS)~~ [d-hayashi,sudach]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by hdl-service** [comment]
New changes are detected. LGTM label has been removed.

**Review by sudach — APPROVED** [review]
コンフリ対応しました。
LGTM付けておけば良いのかな。

**Comment by hdl-service** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/dataware-tools/pydtk/pull/77#" title="Author self-approved">d-hayashi</a>*, *<a href="https://github.com/dataware-tools/pydtk/pull/77#pullrequestreview-709168841" title="Approved">sudach</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=dataware-tools%2Fpydtk).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/dataware-tools/pydtk/blob/master/OWNERS)~~ [d-hayashi,sudach]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by d-hayashi** [comment]
@sudach コンフリクト解消あざます！

**Pull request merged**
